# 200Mhz
set_property PACKAGE_PIN Y52 [get_ports ddr4_sys_diff_clock_clk_p]
set_property PACKAGE_PIN Y53 [get_ports ddr4_sys_diff_clock_clk_n]

# MEM_ADDRESS
set_property -dict {PACKAGE_PIN AC46 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[0]}]
set_property -dict {PACKAGE_PIN Y47 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[1]}]
set_property -dict {PACKAGE_PIN Y45 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[2]}]
set_property -dict {PACKAGE_PIN AA46 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[3]}]
set_property -dict {PACKAGE_PIN W53 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[4]}]
set_property -dict {PACKAGE_PIN W52 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[5]}]
set_property -dict {PACKAGE_PIN Y49 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[6]}]
set_property -dict {PACKAGE_PIN AA49 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[7]}]
set_property -dict {PACKAGE_PIN Y50 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[8]}]
set_property -dict {PACKAGE_PIN AA47 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[9]}]
set_property -dict {PACKAGE_PIN AC48 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[10]}]
set_property -dict {PACKAGE_PIN AA45 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[11]}]
set_property -dict {PACKAGE_PIN V51 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[12]}]
set_property -dict {PACKAGE_PIN AC51 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[13]}]
# MEM_WE_N port not available.
# set_property -dict {PACKAGE_PIN AB46 IOSTANDARD SSTL12_DCI} [get_ports ddr4_mem_we_n]
set_property -dict {PACKAGE_PIN AB46 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[14]}]
# MEM_CAS_N port not available.
# set_property -dict {PACKAGE_PIN AC49 IOSTANDARD SSTL12_DCI} [get_ports u0_dom_ddrssu0_ddr45PAD_MEM_CAS_N]
set_property -dict {PACKAGE_PIN AC49 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[15]}]
# MEM_RAS_N port not available.
# set_property -dict {PACKAGE_PIN AC50 IOSTANDARD SSTL12_DCI} [get_ports u0_dom_ddrssu0_ddr45PAD_MEM_RAS_N]
set_property -dict {PACKAGE_PIN AC50 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_adr[16]}]

set_property -dict {PACKAGE_PIN AB49 IOSTANDARD SSTL12_DCI} [get_ports ddr4_sdram_act_n]
set_property -dict {PACKAGE_PIN AB47 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_ba[0]}]
set_property -dict {PACKAGE_PIN Y54 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_ba[1]}]
set_property -dict {PACKAGE_PIN W51 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_bg[0]}]
set_property -dict {PACKAGE_PIN W55 IOSTANDARD SSTL12_DCI} [get_ports {ddr4_sdram_bg[1]}]
# MEM_CLK (inverted)
set_property -dict {PACKAGE_PIN AB52 IOSTANDARD DIFF_SSTL12_DCI} [get_ports ddr4_sdram_ck_c]
# MEM_CLK_N (inverted)
set_property -dict {PACKAGE_PIN AB51 IOSTANDARD DIFF_SSTL12_DCI} [get_ports ddr4_sdram_ck_t]
# MEM_CKE
set_property -dict {PACKAGE_PIN V53 IOSTANDARD SSTL12_DCI} [get_ports ddr4_sdram_cke]
# MEM_CS_N
set_property -dict {PACKAGE_PIN W56 IOSTANDARD SSTL12_DCI} [get_ports ddr4_sdram_cs_n]
# MEM_DM
set_property -dict {PACKAGE_PIN AH58 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[0]}]
set_property -dict {PACKAGE_PIN AC53 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[1]}]
set_property -dict {PACKAGE_PIN AB61 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[2]}]
set_property -dict {PACKAGE_PIN U56 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[3]}]
set_property -dict {PACKAGE_PIN W60 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[4]}]
set_property -dict {PACKAGE_PIN P57 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[5]}]
set_property -dict {PACKAGE_PIN M53 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[6]}]
set_property -dict {PACKAGE_PIN R52 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dm_n[7]}]
# MEM_DATA
set_property -dict {PACKAGE_PIN AG59 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[0]}]
set_property -dict {PACKAGE_PIN AF62 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[1]}]
set_property -dict {PACKAGE_PIN AG61 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[2]}]
set_property -dict {PACKAGE_PIN AF59 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[3]}]
set_property -dict {PACKAGE_PIN AG58 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[4]}]
set_property -dict {PACKAGE_PIN AF61 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[5]}]
set_property -dict {PACKAGE_PIN AF60 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[6]}]
set_property -dict {PACKAGE_PIN AE62 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[7]}]
set_property -dict {PACKAGE_PIN AC55 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[8]}]
set_property -dict {PACKAGE_PIN AB53 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[9]}]
set_property -dict {PACKAGE_PIN AA57 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[10]}]
set_property -dict {PACKAGE_PIN AB56 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[11]}]
set_property -dict {PACKAGE_PIN AB54 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[12]}]
set_property -dict {PACKAGE_PIN AA56 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[13]}]
set_property -dict {PACKAGE_PIN AC56 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[14]}]
set_property -dict {PACKAGE_PIN AB57 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[15]}]
set_property -dict {PACKAGE_PIN AB59 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[16]}]
set_property -dict {PACKAGE_PIN AA59 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[17]}]
set_property -dict {PACKAGE_PIN AA62 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[18]}]
set_property -dict {PACKAGE_PIN Y62 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[19]}]
set_property -dict {PACKAGE_PIN AA60 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[20]}]
set_property -dict {PACKAGE_PIN AB58 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[21]}]
set_property -dict {PACKAGE_PIN AA61 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[22]}]
set_property -dict {PACKAGE_PIN Y63 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[23]}]
set_property -dict {PACKAGE_PIN T57 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[24]}]
set_property -dict {PACKAGE_PIN R55 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[25]}]
set_property -dict {PACKAGE_PIN P55 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[26]}]
set_property -dict {PACKAGE_PIN R58 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[27]}]
set_property -dict {PACKAGE_PIN T56 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[28]}]
set_property -dict {PACKAGE_PIN P56 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[29]}]
set_property -dict {PACKAGE_PIN R54 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[30]}]
set_property -dict {PACKAGE_PIN R57 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[31]}]
set_property -dict {PACKAGE_PIN U63 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[32]}]
set_property -dict {PACKAGE_PIN W62 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[33]}]
set_property -dict {PACKAGE_PIN W63 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[34]}]
set_property -dict {PACKAGE_PIN V59 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[35]}]
set_property -dict {PACKAGE_PIN V63 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[36]}]
set_property -dict {PACKAGE_PIN V58 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[37]}]
set_property -dict {PACKAGE_PIN U61 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[38]}]
set_property -dict {PACKAGE_PIN U62 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[39]}]
set_property -dict {PACKAGE_PIN N56 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[40]}]
set_property -dict {PACKAGE_PIN N58 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[41]}]
set_property -dict {PACKAGE_PIN K57 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[42]}]
set_property -dict {PACKAGE_PIN L57 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[43]}]
set_property -dict {PACKAGE_PIN M57 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[44]}]
set_property -dict {PACKAGE_PIN M58 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[45]}]
set_property -dict {PACKAGE_PIN N55 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[46]}]
set_property -dict {PACKAGE_PIN K58 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[47]}]
set_property -dict {PACKAGE_PIN K54 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[48]}]
set_property -dict {PACKAGE_PIN J52 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[49]}]
set_property -dict {PACKAGE_PIN J51 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[50]}]
set_property -dict {PACKAGE_PIN M51 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[51]}]
set_property -dict {PACKAGE_PIN M52 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[52]}]
set_property -dict {PACKAGE_PIN L54 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[53]}]
set_property -dict {PACKAGE_PIN L52 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[54]}]
set_property -dict {PACKAGE_PIN L51 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[55]}]
set_property -dict {PACKAGE_PIN P52 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[56]}]
set_property -dict {PACKAGE_PIN T51 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[57]}]
set_property -dict {PACKAGE_PIN U53 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[58]}]
set_property -dict {PACKAGE_PIN U52 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[59]}]
set_property -dict {PACKAGE_PIN P51 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[60]}]
set_property -dict {PACKAGE_PIN P53 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[61]}]
set_property -dict {PACKAGE_PIN N51 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[62]}]
set_property -dict {PACKAGE_PIN T52 IOSTANDARD POD12_DCI} [get_ports {ddr4_sdram_dq[63]}]
# DQS_N (inverted)
set_property -dict {PACKAGE_PIN AG62 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[0]}]
set_property -dict {PACKAGE_PIN AA54 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[1]}]
set_property -dict {PACKAGE_PIN Y59 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[2]}]
set_property -dict {PACKAGE_PIN T54 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[3]}]
set_property -dict {PACKAGE_PIN V60 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[4]}]
set_property -dict {PACKAGE_PIN M56 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[5]}]
set_property -dict {PACKAGE_PIN K52 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[6]}]
set_property -dict {PACKAGE_PIN N53 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_t[7]}]
# DQS_P (inverted)
set_property -dict {PACKAGE_PIN AG63 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[0]}]
set_property -dict {PACKAGE_PIN AA55 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[1]}]
set_property -dict {PACKAGE_PIN Y60 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[2]}]
set_property -dict {PACKAGE_PIN T55 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[3]}]
set_property -dict {PACKAGE_PIN V61 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[4]}]
set_property -dict {PACKAGE_PIN L56 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[5]}]
set_property -dict {PACKAGE_PIN K53 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[6]}]
set_property -dict {PACKAGE_PIN N54 IOSTANDARD DIFF_POD12_DCI} [get_ports {ddr4_sdram_dqs_c[7]}]
# MEM_ODT
set_property -dict {PACKAGE_PIN V56 IOSTANDARD SSTL12_DCI} [get_ports ddr4_sdram_odt]
# MEM_RESET_N
set_property -dict {PACKAGE_PIN Y48 IOSTANDARD LVCMOS12 DRIVE 8} [get_ports ddr4_sdram_reset_n]